name: Build and Deploy
run-name: ${{ gitea.actor }} Running build and deploy
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The name of your branch is ${{ gitea.ref }} and your repository is ${{ gitea.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ gitea.repository }} repository has been cloned to the runner."
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy      
      - run: echo "This job's status is ${{ gitea.status }}."