name: Build and Deploy
run-name: ${{ gitea.actor }} Running build and deploy
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "The ${{ gitea.repository }} repository has been cloned to the runner."
      - name: Create env file production
        run: |
          touch .env.production
          echo "REACT_APP_GOOGLE_CLIENT_ID=$REACT_APP_GOOGLE_CLIENT_ID" >> .env.production
          echo "REACT_APP_API_URL=$REACT_APP_API_URL" >> .env.production
          cat .env.production
        env:
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}     
        - name: Create env file development
        run: |
          touch .env.development
          echo "SFTP_SERVER=$SFTP_SERVER" >> .env.development
          echo "SFTP_USER=$SFTP_USER" >> .env.development
          echo "SFTP_PASSWORD=$SFTP_PASSWORD" >> .env.development
          echo "SFTP_PORT=$SFTP_PORT" >> .env.development
        env:
          SFTP_SERVER: ${{ secrets.SFTP_SERVER }}
          SFTP_USER: ${{ secrets.SFTP_USER }}
          SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
          SFTP_PORT: ${{ secrets.SFTP_PORT }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: View build folder
        run: |
          ls -a ${{ gitea.workspace }}/build
      - name: Deploy
        run: npm run deploy
      - run: echo "This job's status is ${{ gitea.status }}."